alb:
- name: alb
  from_port: 80
  to_port: 80

frontend:
- name: frontend
  from_port: 80
  to_port: 80
- name: frontend_alb
  src: alb
  dest: frontend
  port: 80

backend:
- name: backend
  from_port: 8000
  to_port: 8000
- name: backend_alb
  src: alb
  dest: backend
  port: 8000