name: Demo github actions file
on:
    workflow_dispatch: 
        inputs:
            environment:
                description: Environment field.
                required: true
                default: "dev"
                type: choice
                options:
                    - "dev"
                    - "uat"
                    - "prod"
# workflow level
# job level
# step level
env:
    DOCKERURL: "docker.io"

jobs:

    debug_job:
        runs-on: ubuntu-latest
        steps:
            -   name: print
                run: |
                    echo "Starting..."
                    echo "Ending"
            - name: print2
              run: echo "printingggg"
            - name: accessing env variable
              run: |
                echo ${{ env.DOCKERURL }}
    output_job:
        runs-on: ubuntu-latest
        needs: debug_job
        steps:
            -   name: output name
                run: |
                    echo "Name output"
            -   name: output gender
                run: |
                    echo "Gender output"
            - name: accessing env variable
              run: |
                echo ${{ env.DOCKERURL }}

