name: Demo github actions file
on:
    workflow_dispatch: 
        inputs:
            environment:
                description: Environment field.
                required: true
                default: "dev"
                type: choice
                options:
                    - "dev"
                    - "uat"
                    - "prod"
# workflow level
# job level
# step level
env:
    DOCKERURL: "docker.io"

jobs:

    debug_job:
        runs-on: ubuntu-latest
        env:
            debug_job_priority: "1"
        steps:
            -   name: print
                run: |
                    echo "Starting..."
                    echo "Ending"
                    echo "Job level variable - debug_job_priority :: ${{env.debug_job_priority}}"
            - name: print2
              run: echo "printingggg"
            - name: accessing env variable
              run: |
                echo ${{ env.DOCKERURL }}
                echo "Job level variable - debug_job_priority :: ${{env.debug_job_priority}}"
            - name: update github_output
              id: setting
              run: echo "stage=debug_job" >> $GITHUB_OUTPUT
            - name: getting from github_output
              run: echo ${{ steps.setting.outputs.stage }}
    output_job:
        runs-on: ubuntu-latest
        needs: debug_job
        steps:
            -   name: output name
                run: |
                    echo "Name output"
            -   name: output gender
                run: |
                    echo "Gender output"
            - name: accessing env variable
              run: |
                echo ${{ env.DOCKERURL }}
            - name: accessing env variable from previous job
              run: |
                echo ${{ needs.debug_job.outputs.stage }}

