name: Roboshop Infra AWS - Destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "AWS Infra using Terraform"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "uat"
          - "prod"
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VERSION: 1.15.1

jobs:
  rds:
    name: rds
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: rds
      working-directory: ./40-rds/dev/
    secrets: inherit

  bastion:
    name: Bastion
    needs: rds
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: bastion
      working-directory: ./30-bastion/dev/
    secrets: inherit
    
  sg-rules:
    name: SG Rules
    needs: bastion
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: sg-rules
      working-directory: ./20-sg-rules/dev/
    secrets: inherit

  sg:
    name: SG
    needs: sg-rules
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: sg
      working-directory: ./10-sg/dev/
    secrets: inherit
  
  vpc:
    name: VPC
    needs: sg
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: vpc
      working-directory: ./00-vpc/dev/
    secrets: inherit