name: Todo Infra AWS - Destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "AWS Infra using Terraform"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "uat"
          - "prod"
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VERSION: 1.15.1

jobs:
  rds:
    name: rds
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: rds
      working-directory: ./infra/rds/env/dev/
    secrets: inherit
  ecs:
    name: ecs
    needs: rds
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: ecs
      working-directory: ./infra/ecs/env/dev/
    secrets: inherit

  alb:
    name: alb
    needs: ecs
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: alb
      working-directory: ./infra/alb/env/dev/
    secrets: inherit
    
  sg-rules:
    name: SG Rules
    needs: alb
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: sg-rules
      working-directory: ./infra/sg-rules/env/dev/
    secrets: inherit

  sg:
    name: SG
    needs: sg-rules
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: sg
      working-directory: ./infra/sg/env/dev/
    secrets: inherit
  
  vpc:
    name: VPC
    needs: sg
    uses: ./.github/workflows/terraform-reusable-destroy.yaml
    with:
      service-name: vpc
      working-directory: ./infra/vpc/env/dev/
    secrets: inherit