name: Terraform reusable code for Create
on:
  workflow_call:
    inputs:
      service-name:
        description: "Name of the service"
        required: true
        type: string
      working-directory:
        description: "terraform executable code path"
        required: true
        type: string
      terraform_version:
        description: "terraform version"
        required: false
        default: "1.15.1"
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
  
jobs:
  create:
    name: ${{ inputs.service-name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform init
        run: terraform init --backend-config=backend-dev.hcl -upgrade

      # - name: terraform validate
      #   run: terraform validate

      - name: terraform plan
        run: terraform plan --var-file=dev.tfvars -out=tfplan

      - name: terraform apply 
        run: terraform apply -auto-approve tfplan

